# Generated by Django 4.2.7 on 2023-11-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="attack",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="combat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="durability",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="hp",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="intelligence",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="power",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="speed",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="strength",
            field=models.FloatField(null=True),
        ),
    ]
