# Generated by Django 4.2.7 on 2023-11-30 18:23

from django.db import migrations


TASK_NAME = 'Sync characters'


def create_periodic_sync_task(apps, _):
    PeriodicTask = apps.get_model('django_celery_beat.PeriodicTask')  # noqa: N806
    CrontabSchedule = apps.get_model('django_celery_beat.CrontabSchedule')  # noqa: N806

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='3',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    PeriodicTask.objects.create(
        name=TASK_NAME,
        task='simulation.apps.characters.tasks.sync_characters',
        crontab=schedule,
        kwargs='{"api_id": 1, "sync_next_id": true}',
    )


def delete_periodic_sync_task(apps, _):
    PeriodicTask = apps.get_model('django_celery_beat.PeriodicTask')  # noqa: N806

    PeriodicTask.objects.filter(name=TASK_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('characters', '0002_alter_character_attack_alter_character_combat_and_more'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.RunPython(
            create_periodic_sync_task,
            delete_periodic_sync_task,
        ),
    ]
